target("Tiny-Msgpk")
    set_kind("static")
    add_files("src/*.c|test.cpp")
    add_includedirs("include")

target("test")
    set_kind("binary")
    add_files("src/*.c")
    add_files("src/*.cpp|test_file.cpp")
    add_includedirs("include")

target("test_file")
    set_kind("binary")
    add_files("src/*.c")
    add_files("src/*.cpp|test.cpp")
    add_includedirs("include")